---
deployment:
  tasks:
    - export DEPLOYPATH=/home/victorlu/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp -R scripts $DEPLOYPATH
    - /bin/cp -R styles $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R files $DEPLOYPATH